### ISSUE TITLE
netdiff and olsrd latlon.js

### ISSUE THREAD

**Issue by sp2ong** [ninuxorg/netdiff#42] opened 2016-04-28 04:56 UTC
Maybe it will be possible add when we use OLSRD to create file for netjsongraph use file latlon.js which contain xy coordinates node for exmaple:
....
Node('195.165.33.135',52.026421,15.629709,0,'0.0.0.0','NODE-1');
PLink('195.165.33.254','195.165.33.1',1.000,1.000,0.100,52.015381,15.597080,0,52.015518,15.597071,0);
....

and add this info to "properties": and when crate graph and exit xy coordinates when we clik on graph green line in display properties this link add information distance: between nodes . We can calculate use xy coordinates. It is usefull information about link. In our site weh hav node where links between nodes are form 1.5 km do 9 km

we can add one more option in script where user will define path to latlon.js file

olsrlatlon('/var/run/latlon.js')

or other

**Comment by nemesisdesign** [comment] 2016-04-28 10:18
@sp2ong, I haven't understood very well what you want to do, I only understood you need to process and display geographic coordinates, but this kind of feature does not regard the netdiff library.

This library is in charge of parsing topology formats, harmonize them by converting them to NetJSON and detect changes.

In theory, you could do some preprocessing yourself and add the geographic coordinates in the NetJSON object, BUT there are a few open issues that need to be solved before netdiff can work with this data transparently:

* #39 
* #35

**Comment by nemesisdesign** [comment] 2016-04-30 13:27
Closing this issue because the issue is not specific to netdiff.

**Closed by nemesisdesign** 2016-04-30 13:27 UTC
Labels: question
